### ISSUE TITLE
How to use the script? -- COMPLETE NEWBIE--

### ISSUE THREAD

**Issue by grego1981** [haimkastner/broadlink-ir-converter#1]
Hello and congrats on your implementation, it is exactly what I need!
I'm trying to use the example to recode from tasmota to broadlink for some codes I need. I have saved the code in a js file and try to run it using "node broad.js" command but I get the error:
```
/root/broad.js:1
(function (exports, require, module, __filename, __dirname) { import { broadlinkToPulesArray, pulesArrayToBroadlink } from'broadlink-ir-converter';
                                                              

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by haimkastner** [comment]
You can use the old (CommonJS) import style `require` if you wish.

The code will look like:
```javascript
const broad = require('broadlink-ir-converter');

const broadlinkCommand = '2600920000012991173517101711173417351710171117101711171116351735161117111611171117101711171017111710173517341711171017111710171117341711173417111710173517111600028f1711171116111711161117111611171117101711171017111710171117101711171017111710171117101711171017111710171117111611173516351735163517000d05000000000000';

const pulesArray = [0,8953,4324,609,1522,609,395,609,426,609,1492,609,1522,609,395,609,426,609,395,609,426,609,426,578,1522,609,1522,578,426,609,426,578,426,609,426,609,395,609,426,609,395,609,426,609,395,609,1522,609,1492,609,426,609,395,609,426,609,395,609,426,609,1492,609,426,609,1492,609,426,609,395,609,1522,609,426,578,19855,609,426,609,426,578,426,609,426,578,426,609,426,578,426,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,426,578,426,609,1522,578,1522,609,1522,578,1522,609];

const convertedPulesArray = broad.broadlinkToPulesArray(broadlinkCommand);
const convertedBroadlinkCommand = broad.pulesArrayToBroadlink(pulesArray);


console.log(JSON.stringify(convertedPulesArray)); // [0,8953,4324,609,1522,609,395,609,426,609,1492,609,1522,609,395,609,426,609,395,609,426,609,426,578,1522,609,1522,578,426,609,426,578,426,609,426,609,395,609,426,609,395,609,426,609,395,609,1522,609,1492,609,426,609,395,609,426,609,395,609,426,609,1492,609,426,609,1492,609,426,609,395,609,1522,609,426,578,19855,609,426,609,426,578,426,609,426,578,426,609,426,578,426,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,395,609,426,609,426,578,426,609,1522,578,1522,609,1522,578,1522,609]
console.log(convertedBroadlinkCommand); // '2600920000012991173517101711173417351710171117101711171116351735161117111611171117101711171017111710173517341711171017111710171117341711173417111710173517111600028f1711171116111711161117111611171117101711171017111710171117101711171017111710171117101711171017111710171117111611173516351735163517000d05000000000000
```

But I recommend you to read and use the new import and project style.
You can read about new project creation [here](https://nodejspedia.com/en/tutorial/5934/node-js-with-es6)
You can read about the ES6 import [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)

Also, if you are new in the Node.JS / JS ecosystem, I highly recommend you to read about [TypeScript](https://www.typescriptlang.org/) too.

**Comment by grego1981** [comment]
Thank you on your suggestions! They really pointed me to the right direction! Starting to learn and I made it work. Thank you once again on your invaluable help and your helpful script!
